packages:
  - 'packages/web'
  - 'packages/shared'

overrides:
  esbuild: 0.28.1

allowBuilds:
  esbuild: true
  sharp: true
  workerd: true

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
  - sharp
  - workerd
