import Foundation
import SwiftData

@Model
final class TagEntity {
    @Attribute(.unique) var id: UUID = UUID()
    var name: String
    var confidence: Double?
    @Relationship var links: [LinkEntity] = []

    init(
        name: String,
        confidence: Double? = nil,
        links: [LinkEntity] = []
    ) {
        // id is auto-generated by default
        self.name = name
        self.confidence = confidence
        self.links = links
    }
}
